In [1]:
# Topics:

# LogisticRegression

# Working of LogisticRegression

# Train model on logistic Regression

# calculate training and testing score

# calculate classification report for training and testing dataset



In [2]:
# LogisticRegression:

In [3]:
from sklearn.linear_model import LogisticRegression

In [6]:
import pandas as pd

In [8]:
df=pd.read_csv("Fruit_dataset_10000.csv")

In [16]:
df['name'].value_counts()  # we will use classification beacuse target belong to only two class

orange        5000
grapefruit    5000
Name: name, dtype: int64

In [21]:
# Now we will break dataset df into two part feature called X and target called y
X=df.iloc[:,1:].values
y=df.iloc[:,0].values

In [23]:
X

array([[  2.96,  86.76],
       [  3.91,  88.05],
       [  4.42,  95.17],
       ...,
       [ 15.59, 256.5 ],
       [ 15.92, 260.14],
       [ 16.45, 261.51]])

In [24]:
# scaling 
from sklearn.preprocessing import MinMaxScaler

In [25]:
sc=MinMaxScaler()

In [27]:
X_sc=sc.fit_transform(X)

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X_sc,y)

In [30]:
X_train.shape

(7500, 2)

In [31]:
y_train.shape

(7500,)

In [32]:
X_test.shape

(2500, 2)

In [33]:
y_test.shape

(2500,)

In [34]:
Model=LogisticRegression()

In [35]:
Model.fit(X_train,y_train)

LogisticRegression()

In [38]:
X_train_pred=Model.predict(X_train)

In [39]:
y_train

array(['grapefruit', 'orange', 'grapefruit', ..., 'grapefruit',
       'grapefruit', 'orange'], dtype=object)

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(y_train,X_train_pred)

0.8808

In [45]:
X_test_pred=Model.predict(X_test)

In [46]:
y_test

array(['grapefruit', 'orange', 'orange', ..., 'orange', 'grapefruit',
       'orange'], dtype=object)

In [49]:
accuracy_score(y_test,X_test_pred)

0.8856

In [50]:
Model.score(X_train,y_train)

0.8808

In [51]:
Model.score(X_test,y_test)

0.8856

In [52]:
from sklearn.metrics import classification_report

In [55]:
print(classification_report(y_train,X_train_pred))

              precision    recall  f1-score   support

  grapefruit       0.88      0.88      0.88      3744
      orange       0.88      0.88      0.88      3756

    accuracy                           0.88      7500
   macro avg       0.88      0.88      0.88      7500
weighted avg       0.88      0.88      0.88      7500



In [57]:
Model.coef_

array([[-12.64951191,  -8.64349299]])

In [58]:
Model.intercept_

array([10.95966369])

In [66]:
print(X_train[0])
print(y_train[0])
print(Model.coef_)
print(Model.intercept_)

[0.57894737 0.56972818]
grapefruit
[[-12.64951191  -8.64349299]]
[10.95966369]


In [67]:
# y=m1x1+m2x2+c
y=-12.64951191*0.57894737+(-8.64349299)*0.56972818+10.95966369
print(y)

-1.2881794921136347


In [68]:
# probability using sigmoid function if p<0.5 then class 0 or 1

# P[1]=1/(1+e**(-y))
#P[0]=1/(1+e**(y))

In [78]:
 import math
 P=1/(1+2.718281828459045**(-(-1.2881794921136347)))

In [79]:
print(P)

0.21616111006548228


In [80]:
math.e

2.718281828459045

In [81]:
X_train.pred

AttributeError: 'numpy.ndarray' object has no attribute 'pred'

In [82]:
Model.predict([[0.57894737, 0.56972818]])

array(['grapefruit'], dtype=object)

In [87]:
X_train_pred[:10]

array(['grapefruit', 'orange', 'grapefruit', 'grapefruit', 'grapefruit',
       'grapefruit', 'grapefruit', 'grapefruit', 'grapefruit',
       'grapefruit'], dtype=object)

In [88]:
y_train[:10]

array(['grapefruit', 'orange', 'grapefruit', 'grapefruit', 'grapefruit',
       'orange', 'grapefruit', 'grapefruit', 'grapefruit', 'orange'],
      dtype=object)

In [85]:
X_test_pred

array(['grapefruit', 'orange', 'grapefruit', ..., 'orange', 'grapefruit',
       'orange'], dtype=object)

In [86]:
y_test

array(['grapefruit', 'orange', 'orange', ..., 'orange', 'grapefruit',
       'orange'], dtype=object)

In [89]:
print(X_train[5])
print(y_train[5])
print(Model.coef_)
print(Model.intercept_)

[0.62194218 0.61470672]
orange
[[-12.64951191  -8.64349299]]
[10.95966369]


In [91]:
y=(-12.64951191)* 0.62194218+(-8.64349299)*0.61470672+10.95966369
y

-2.2208145484672563

In [93]:
 import math
 P=1/(1+2.718281828459045**(-(-2.2208145484672563)))
 P

0.09789684547062191

In [94]:
Model.predict([[0.62194218,0.61470672]])

array(['grapefruit'], dtype=object)

In [2]:
# activation function 

    # > sigmoid activation function 
    
    # > softmax activation function  

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("iris.csv")

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
sc=MinMaxScaler()
X_sc=sc.fit_transform(X)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,train_size=0.70,random_state=42)

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
Model=LogisticRegression(max_iter=100,multi_class="ovr")

In [16]:
Model.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [18]:
X_train_pred=Model.predict(X_train)

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
accuracy_score(y_train,X_train_pred)

0.8761904761904762

In [22]:
Model.score(X_test,y_test)

0.8444444444444444

In [26]:
sc=MinMaxScaler()
X_sc=sc.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,train_size=0.70,random_state=3)
Model=LogisticRegression(max_iter=100,multi_class="ovr")
Model.fit(X_train,y_train)
X_train_pred=Model.predict(X_train)
print("Training score:",accuracy_score(y_train,X_train_pred))
print("Testing score :",Model.score(X_test,y_test))

Training score: 0.8952380952380953
Testing score : 0.8888888888888888


In [28]:
for i in range(10):
    print(f"-------------------{i}-----------------")
    sc=MinMaxScaler()
    X_sc=sc.fit_transform(X)
    X_train,X_test,y_train,y_test=train_test_split(X_sc,y,train_size=0.70,random_state=i)
    Model=LogisticRegression(max_iter=100,multi_class="ovr")
    Model.fit(X_train,y_train)
    X_train_pred=Model.predict(X_train)
    print("Training score:",accuracy_score(y_train,X_train_pred))
    print("Testing score :",Model.score(X_test,y_test))

-------------------0-----------------
Training score: 0.8666666666666667
Testing score : 0.7555555555555555
-------------------1-----------------
Training score: 0.8666666666666667
Testing score : 0.7555555555555555
-------------------2-----------------
Training score: 0.8380952380952381
Testing score : 0.8888888888888888
-------------------3-----------------
Training score: 0.8952380952380953
Testing score : 0.8888888888888888
-------------------4-----------------
Training score: 0.9047619047619048
Testing score : 0.9555555555555556
-------------------5-----------------
Training score: 0.8571428571428571
Testing score : 0.8444444444444444
-------------------6-----------------
Training score: 0.9142857142857143
Testing score : 0.9111111111111111
-------------------7-----------------
Training score: 0.9142857142857143
Testing score : 0.8222222222222222
-------------------8-----------------
Training score: 0.9047619047619048
Testing score : 0.7555555555555555
-------------------9--------

In [29]:
for i in range(10):
    print(f"-------------------{i}-----------------")
    sc=MinMaxScaler()
    X_sc=sc.fit_transform(X)
    X_train,X_test,y_train,y_test=train_test_split(X_sc,y,train_size=0.70,random_state=i)
    Model=LogisticRegression(max_iter=100,multi_class="multinomial")
    Model.fit(X_train,y_train)
    X_train_pred=Model.predict(X_train)
    print("Training score:",accuracy_score(y_train,X_train_pred))
    print("Testing score :",Model.score(X_test,y_test))

-------------------0-----------------
Training score: 0.9142857142857143
Testing score : 0.8888888888888888
-------------------1-----------------
Training score: 0.9238095238095239
Testing score : 0.9111111111111111
-------------------2-----------------
Training score: 0.9047619047619048
Testing score : 0.9555555555555556
-------------------3-----------------
Training score: 0.9238095238095239
Testing score : 0.9333333333333333
-------------------4-----------------
Training score: 0.9333333333333333
Testing score : 0.9777777777777777
-------------------5-----------------
Training score: 0.9238095238095239
Testing score : 0.9111111111111111
-------------------6-----------------
Training score: 0.9428571428571428
Testing score : 0.9333333333333333
-------------------7-----------------
Training score: 0.9523809523809523
Testing score : 0.8444444444444444
-------------------8-----------------
Training score: 0.9523809523809523
Testing score : 0.8222222222222222
-------------------9--------

In [30]:
# Polynomial feature
# Regularization 
    # >Ridge
    # >Lasso

# DecisionTree

In [31]:
# polynomial feature

In [33]:
df1=pd.DataFrame({"height":[34,43,21,43,54,5,7,8,10,11],
              "Target":["Apple","Apple","Apple","Apple","Apple","Banana","Banana","Banana","Banana","Banana"]})

In [34]:
X=df1.iloc[:,:-1].values

In [37]:
y=df1.iloc[:,-1].values

In [38]:
Model2=LogisticRegression()

In [39]:
Model2.fit(X,y)

LogisticRegression()

In [41]:
Model2.predict(X)

array(['Apple', 'Apple', 'Apple', 'Apple', 'Apple', 'Banana', 'Banana',
       'Banana', 'Banana', 'Banana'], dtype=object)

In [42]:
y

array(['Apple', 'Apple', 'Apple', 'Apple', 'Apple', 'Banana', 'Banana',
       'Banana', 'Banana', 'Banana'], dtype=object)

In [43]:
Model2.predict([[15]])

array(['Banana'], dtype=object)

In [44]:
X

array([[34],
       [43],
       [21],
       [43],
       [54],
       [ 5],
       [ 7],
       [ 8],
       [10],
       [11]], dtype=int64)

In [45]:
from sklearn.preprocessing import PolynomialFeatures

In [53]:
feature=PolynomialFeatures(degree=100)

In [55]:
a=feature.fit_transform(X)

In [57]:
len(a[0])

101

In [64]:
a
sc=MinMaxScaler()
a_sc=sc.fit_transform(a)
a_sc

array([[0.00000000e+00, 5.91836735e-01, 3.91214113e-01, ...,
        2.04336245e-20, 1.28656154e-20, 8.10057266e-21],
       [0.00000000e+00, 7.75510204e-01, 6.30923556e-01, ...,
        2.01985496e-10, 1.60840302e-10, 1.28076537e-10],
       [0.00000000e+00, 3.26530612e-01, 1.43894846e-01, ...,
        6.35188200e-41, 2.47017633e-41, 9.60624129e-42],
       ...,
       [0.00000000e+00, 6.12244898e-02, 1.34901418e-02, ...,
        5.34847860e-82, 7.92367200e-83, 1.17387733e-83],
       [0.00000000e+00, 1.02040816e-01, 2.59425804e-02, ...,
        1.68039561e-72, 3.11184372e-73, 5.76267355e-74],
       [0.00000000e+00, 1.22448980e-01, 3.32065029e-02, ...,
        1.91379177e-68, 3.89846472e-69, 7.94131702e-70]])

In [70]:
Model3=LogisticRegression(max_iter=100)
Model3.fit(a_sc,y)

LogisticRegression()