In [1]:
print("hello world")

hello world


In [2]:
pip install pandas


[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import pandas as pd

In [5]:
df=pd.read_csv("project_sal.csv")

In [6]:
df

YearsExperience  Projects  Salary
0               1.1         1   39343
1               1.3         2   46205
2               1.5         1   37731
3               2.0         2   43525
4               2.2         1   39891
5               2.9         4   56642
6               3.0         4   60150
7               3.2         3   54445
8               3.2         5   64445
9               3.7         2   57189
10              3.9         4   63218
11              4.0         7   55794
12              4.0         8   56957
13              4.1         8   57081
14              4.5         9   61111
15              4.9        10   67938
16              5.1         8   66029
17              5.3        11   83088
18              5.9         9   81363
19              6.0        12   93940
20              6.8         6   91738
21              7.1         7   98273
22              7.9        11  101302
23              8.2         6  113812
24              8.7         5  109431
25              9.0         5  105582
26              9.5         6  116969
27              9.6         8  112635
28             10.3        10  122391
29             10.5        11  121872
30             11.2         4  127345
31             11.5         8  126756
32             12.3         7  128765
33             12.9         5  135675
34             13.5         9  139465

In [10]:
X=df.iloc[:,:-1].values    # this is feature matrix

In [16]:
y=df.iloc[:,-1].values   #target

In [17]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
model=LinearRegression()       #

In [20]:
model.fit(X,y)

LinearRegression()

In [21]:
model.predict([[3,3]])

array([54426.57824778])

In [22]:
model.predict([[4,3]])

array([63019.94233865])

In [23]:
model.predict([[4,4]])

array([63353.75110712])

In [24]:
model.coef_

array([8593.36409087,  333.80876847])

In [25]:
model.intercept_

27645.05966978035

In [26]:
# y=m1x1+m2x2+c
8593.36409087*4+333.80876847*4+27645.05966978035

63353.75110714035

In [27]:
df

YearsExperience  Projects  Salary
0               1.1         1   39343
1               1.3         2   46205
2               1.5         1   37731
3               2.0         2   43525
4               2.2         1   39891
5               2.9         4   56642
6               3.0         4   60150
7               3.2         3   54445
8               3.2         5   64445
9               3.7         2   57189
10              3.9         4   63218
11              4.0         7   55794
12              4.0         8   56957
13              4.1         8   57081
14              4.5         9   61111
15              4.9        10   67938
16              5.1         8   66029
17              5.3        11   83088
18              5.9         9   81363
19              6.0        12   93940
20              6.8         6   91738
21              7.1         7   98273
22              7.9        11  101302
23              8.2         6  113812
24              8.7         5  109431
25              9.0         5  105582
26              9.5         6  116969
27              9.6         8  112635
28             10.3        10  122391
29             10.5        11  121872
30             11.2         4  127345
31             11.5         8  126756
32             12.3         7  128765
33             12.9         5  135675
34             13.5         9  139465

In [28]:
# 1.1	1	39343
model.predict([[1.1,1]])

array([37431.5689382])

In [29]:
# KNN:

In [30]:
df1=pd.read_excel("fruit.xlsx")

In [31]:
df1

width  height Fruitname
0     20      18     Apple
1     21      22     Apple
2     12      11     Apple
3     43      34     Apple
4     32      15     Apple
5      5      50    Banana
6      2      10    Banana
7      3      18    Banana
8     10      15    Banana
9      1      10    Banana

In [32]:
X1=df1.iloc[:,:-1].values

In [34]:
X1

array([[20, 18],
       [21, 22],
       [12, 11],
       [43, 34],
       [32, 15],
       [ 5, 50],
       [ 2, 10],
       [ 3, 18],
       [10, 15],
       [ 1, 10]], dtype=int64)

In [35]:
y1=df1.iloc[:,-1].values

In [36]:
y1

array(['Apple', 'Apple', 'Apple', 'Apple', 'Apple', 'Banana', 'Banana',
       'Banana', 'Banana', 'Banana'], dtype=object)

In [37]:
from sklearn.neighbors import KNeighborsClassifier

In [38]:
model1=KNeighborsClassifier()

In [39]:
model1.fit(X1,y1)

KNeighborsClassifier()

In [41]:
model1.predict([[2.343,10.232]])

array(['Banana'], dtype=object)

In [44]:
y1_pred=model1.predict(X1)
y1_pred

array(['Apple', 'Apple', 'Banana', 'Apple', 'Apple', 'Banana', 'Banana',
       'Banana', 'Banana', 'Banana'], dtype=object)

In [43]:
y1

array(['Apple', 'Apple', 'Apple', 'Apple', 'Apple', 'Banana', 'Banana',
       'Banana', 'Banana', 'Banana'], dtype=object)

In [45]:
from sklearn.metrics import accuracy_score

In [46]:
accuracy_score(y1_pred,y1)

0.9

In [1]:
# KNN--> KNeighborsClassifier
# X --> Feature
# y --> Target
# model --> model.fit(X,y)
# prediction --> y1_pred
# accuracy_score


In [2]:
#Create training dataset 
#create testing dataset
#train_test_split
# Confusion Matrix --> Binary class confusion matrix and multiclass confusion matrix
# Precision score
# Recall Score 
# F1 Score
# Classfication report

In [3]:
import pandas as pd

In [8]:
df=pd.read_csv("Fruit_dataset_10000.csv")
df

name  diameter  weight
0         orange      2.96   86.76
1         orange      3.91   88.05
2         orange      4.42   95.17
3         orange      4.47   95.60
4         orange      4.48   95.76
...          ...       ...     ...
9995  grapefruit     15.35  253.89
9996  grapefruit     15.41  254.67
9997  grapefruit     15.59  256.50
9998  grapefruit     15.92  260.14
9999  grapefruit     16.45  261.51

[10000 rows x 3 columns]

In [9]:
#split into feature X, target y
X=df.iloc[0::1,1::1].values

In [10]:
y=df.iloc[0::1,0].values

In [11]:
y

array(['orange', 'orange', 'orange', ..., 'grapefruit', 'grapefruit',
       'grapefruit'], dtype=object)

In [21]:
#Create training dataset  75%
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y)

#create testing dataset   25%

In [23]:
len(X_train)

7500

In [24]:
len(y_train)

7500

In [27]:
df['name'].value_counts().index

Index(['orange', 'grapefruit'], dtype='object')

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
model =KNeighborsClassifier()

In [30]:
model.fit(X_train,y_train)

KNeighborsClassifier()

In [33]:
y_pred=model.predict(X_train)

In [32]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy_score(y_train,y_pred)

0.9770666666666666

In [35]:
X_test

array([[  6.99, 131.25],
       [  9.04, 161.31],
       [ 10.05, 176.59],
       ...,
       [ 11.47, 197.71],
       [  8.37, 150.9 ],
       [  9.69, 169.41]])

In [36]:
len(X_test)

2500

In [37]:
y_test

array(['orange', 'orange', 'orange', ..., 'grapefruit', 'orange',
       'grapefruit'], dtype=object)

In [38]:
len(y_test)

2500

In [40]:
y_test_pred=model.predict(X_test)

In [41]:
accuracy_score(y_test_pred,y_test)

0.9656

In [42]:
df=pd.read_csv("Fruit_dataset_10000.csv")
#split into feature X, target y
X=df.iloc[0::1,1::1].values
y=df.iloc[0::1,0].values
#Create training dataset  75%
#create testing dataset   25%
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y)

from sklearn.neighbors import KNeighborsClassifier

model =KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_train)
from sklearn.metrics import accuracy_score
print("Training score :",accuracy_score(y_train,y_pred))
y_test_pred=model.predict(X_test)
print("Testing accuracy :",accuracy_score(y_test_pred,y_test))

Training score : 0.9781333333333333
Testing accuracy : 0.9672


In [44]:
df=pd.read_csv("Fruit_dataset_10000.csv")
#split into feature X, target y
X=df.iloc[0::1,1::1].values
y=df.iloc[0::1,0].values
#Create training dataset  75%
#create testing dataset   25%
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42)

from sklearn.neighbors import KNeighborsClassifier

model =KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_train)
from sklearn.metrics import accuracy_score
print("Training score :",accuracy_score(y_train,y_pred))
y_test_pred=model.predict(X_test)
print("Testing accuracy :",accuracy_score(y_test_pred,y_test))

Training score : 0.9777333333333333
Testing accuracy : 0.9616


In [45]:
df=pd.read_csv("Fruit_dataset_10000.csv")
#split into feature X, target y
X=df.iloc[0::1,1::1].values
y=df.iloc[0::1,0].values
#Create training dataset  75%
#create testing dataset   25%
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42)

from sklearn.neighbors import KNeighborsClassifier

model =KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_train)
from sklearn.metrics import accuracy_score
print("Training score :",accuracy_score(y_train,y_pred))
y_test_pred=model.predict(X_test)
print("Testing accuracy :",accuracy_score(y_test_pred,y_test))

Training score : 0.9777333333333333
Testing accuracy : 0.9616


In [1]:
# bias   --> 100% data -actual Training score= Bias ; 100-95=5
# varience --> Training score -testing score =Varience ; 95-92=3
# underfitting 
# overfitting
# Create training dataset ---> complete
# create testing dataset  ---> complete
# train_test_split        ---> complete
# scaling
# Confusion Matrix --> Binary class confusion matrix and multiclass confusion matrix
# Precision score
# Recall Score 
# F1 Score
# Classfication report

In [94]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

df=pd.read_csv("Fruit_dataset_10000.csv")
#split into feature X, target y
X=df.iloc[0::1,1::1].values
y=df.iloc[0::1,0].values
#Create training dataset  75%
#create testing dataset   25%
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42)
model =KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_train)
print("Training score :",accuracy_score(y_train,y_pred))
y_test_pred=model.predict(X_test)
print("Testing accuracy :",accuracy_score(y_test_pred,y_test))

Training score : 0.9777333333333333
Testing accuracy : 0.9616


In [95]:
for i in range(10):
    # print(40*"_"+f"i"+40*"_")
    print(f"--------------------{i}--------------------")
    X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=i)
    model =KNeighborsClassifier()
    model.fit(X_train,y_train)
    y_pred=model.predict(X_train)
    print("Training score :",accuracy_score(y_train,y_pred))
    y_test_pred=model.predict(X_test)
    print("Testing accuracy :",accuracy_score(y_test_pred,y_test))

--------------------0--------------------
Training score : 0.9778666666666667
Testing accuracy : 0.9648
--------------------1--------------------
Training score : 0.9790666666666666
Testing accuracy : 0.9648
--------------------2--------------------
Training score : 0.9753333333333334
Testing accuracy : 0.9632
--------------------3--------------------
Training score : 0.9768
Testing accuracy : 0.9652
--------------------4--------------------
Training score : 0.9770666666666666
Testing accuracy : 0.9624
--------------------5--------------------
Training score : 0.9774666666666667
Testing accuracy : 0.9648
--------------------6--------------------
Training score : 0.9776
Testing accuracy : 0.9648
--------------------7--------------------
Training score : 0.9782666666666666
Testing accuracy : 0.9648
--------------------8--------------------
Training score : 0.9786666666666667
Testing accuracy : 0.9648
--------------------9--------------------
Training score : 0.9769333333333333
Testing ac

In [96]:
df

name  diameter  weight
0         orange      2.96   86.76
1         orange      3.91   88.05
2         orange      4.42   95.17
3         orange      4.47   95.60
4         orange      4.48   95.76
...          ...       ...     ...
9995  grapefruit     15.35  253.89
9996  grapefruit     15.41  254.67
9997  grapefruit     15.59  256.50
9998  grapefruit     15.92  260.14
9999  grapefruit     16.45  261.51

[10000 rows x 3 columns]

In [97]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [98]:
np.max(a)

5

In [99]:
a/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [100]:
X

array([[  2.96,  86.76],
       [  3.91,  88.05],
       [  4.42,  95.17],
       ...,
       [ 15.59, 256.5 ],
       [ 15.92, 260.14],
       [ 16.45, 261.51]])

In [101]:
from sklearn.preprocessing import MinMaxScaler

In [102]:
sc=MinMaxScaler()

In [103]:
sc.fit_transform(X)

array([[0.        , 0.        ],
       [0.07042254, 0.00738197],
       [0.10822832, 0.04812589],
       ...,
       [0.93624907, 0.97133047],
       [0.96071164, 0.99216023],
       [1.        , 1.        ]])

In [104]:
df1=pd.DataFrame(X)
df2=df1.iloc[:,0].values
np.max(df2)

16.45

In [105]:
np.min(df2)

2.96

In [106]:
(df2-2.96)/(np.max(df2)-2.96)

array([0.        , 0.07042254, 0.10822832, ..., 0.93624907, 0.96071164,
       1.        ])

In [107]:
np.array([1,2,3,4,5])-2

array([-1,  0,  1,  2,  3])

In [108]:
np.max(df2-2.96)

13.489999999999998

In [109]:
2.96+13.489999999999998

16.45

In [110]:
from sklearn.preprocessing import MinMaxScaler

In [111]:
sc=MinMaxScaler()

In [112]:
X_sc=sc.fit_transform(X)
X_sc

array([[0.        , 0.        ],
       [0.07042254, 0.00738197],
       [0.10822832, 0.04812589],
       ...,
       [0.93624907, 0.97133047],
       [0.96071164, 0.99216023],
       [1.        , 1.        ]])

In [113]:
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,random_state=42)
model =KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_train)
print("Training score :",accuracy_score(y_train,y_pred))
y_test_pred=model.predict(X_test)
print("Testing accuracy :",accuracy_score(y_test_pred,y_test))

Training score : 0.9970666666666667
Testing accuracy : 0.994


In [114]:
sample= [[3.91,88.05]]
sample_sc=sc.transform(sample)
model.predict(sample_sc)

array(['orange'], dtype=object)

In [115]:
df

name  diameter  weight
0         orange      2.96   86.76
1         orange      3.91   88.05
2         orange      4.42   95.17
3         orange      4.47   95.60
4         orange      4.48   95.76
...          ...       ...     ...
9995  grapefruit     15.35  253.89
9996  grapefruit     15.41  254.67
9997  grapefruit     15.59  256.50
9998  grapefruit     15.92  260.14
9999  grapefruit     16.45  261.51

[10000 rows x 3 columns]

In [116]:
df

name  diameter  weight
0         orange      2.96   86.76
1         orange      3.91   88.05
2         orange      4.42   95.17
3         orange      4.47   95.60
4         orange      4.48   95.76
...          ...       ...     ...
9995  grapefruit     15.35  253.89
9996  grapefruit     15.41  254.67
9997  grapefruit     15.59  256.50
9998  grapefruit     15.92  260.14
9999  grapefruit     16.45  261.51

[10000 rows x 3 columns]

In [117]:
df.name.value_counts().index

Index(['orange', 'grapefruit'], dtype='object')

In [118]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_train)

array([[3772,   22],
       [   0, 3706]], dtype=int64)

In [119]:
y_train

array(['orange', 'orange', 'grapefruit', ..., 'grapefruit', 'orange',
       'grapefruit'], dtype=object)

In [122]:
a=[]
for i in y_train:
    if i=="orange":
        a.append(i)
print(len(a))


3728


In [91]:
y_train

array([1, 1, 'grapefruit', ..., 'grapefruit', 1, 'grapefruit'],
      dtype=object)

In [1]:
# confusion_matrix-->1. binary class confusion matrix
                    #  2. Multiclass confusion matrix

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("iris.csv")

In [4]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
from sklearn.datasets import load_iris

In [17]:
data=load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [22]:
X=data['data']
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [11]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [13]:
df.corr()

C:\Users\Ducat\AppData\Local\Temp\ipykernel_7636\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000

In [18]:
y=data['target']
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
model=KNeighborsClassifier()

In [23]:
model.fit(X,y)

KNeighborsClassifier()

In [27]:
X_pred=model.predict(X)
X_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [28]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
model.predict([[3.4,3,6,12]])

array([2])

In [25]:
from sklearn.metrics import accuracy_score

In [30]:
145/150

0.9666666666666667

In [31]:
accuracy_score(X_pred,y)

0.9666666666666667

In [32]:
# classficiation score

    # precision score,
    # recall score
    # F1_score
    # classification report 
    # accuracy_score

In [33]:
from sklearn.metrics import confusion_matrix

In [35]:
confusion_matrix(y,X_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  2, 48]], dtype=int64)

In [46]:
from sklearn.metrics import classification_report,recall_score,precision_score,f1_score,confusion_matrix

In [48]:
print(classification_report(y,X_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.96      0.94      0.95        50
           2       0.94      0.96      0.95        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97       150



In [50]:
precision_score(y,X_pred,average=None)

array([1.        , 0.95918367, 0.94117647])

In [52]:
recall_score(y,X_pred,average=None)

array([1.  , 0.94, 0.96])

In [54]:
f1_score(y,X_pred,average=None)

array([1.        , 0.94949495, 0.95049505])