In [1]:
# Multi collinear regression
# Regularization: is a technique/ process which handle multi collinearity problem.
# To solve regularization problem we have two techniques:

# Ridge regression

# Lasso regression

# Note: beacuse of high correlataion in the feature coloums we observer "overfitting" very frequent.

# 1> Ridge regression: It will calculate the corelation between the feature column and keep one column as it is. And other feature correlation will be shrink.

# 2> beacause of the shrinking of the corelation the importance of the feature will be minimum for the target.

# 2> Lasso Regression:

# Description: lasso regression state that when we have feature in the data then we donot consider that feature we consider only one feature and train the model.

# Lasso is also called feature section technique in the segement of regression.

In [2]:
import pandas as pd

In [5]:
df1=pd.read_csv("winequality-red.csv")

In [9]:
X=df1.iloc[:,1:].values
y=df1.iloc[:,0].values

In [14]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
X_sc=sc.fit_transform(X)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,random_state=42)

In [18]:
X_train
y

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [13]:
from sklearn.linear_model import Ridge

In [49]:
Model1=Ridge(alpha=1)
Model1.fit(X_train,y_train)

Ridge(alpha=1)

In [50]:
sample=X_sc[1]
sample

array([0.52054795, 0.        , 0.11643836, 0.14357262, 0.33802817,
       0.2155477 , 0.49412628, 0.36220472, 0.20958084, 0.21538462,
       0.4       ])

In [51]:
Model1.predict([sample])

array([7.95659916])

In [52]:
X

array([[ 0.7  ,  0.   ,  1.9  , ...,  0.56 ,  9.4  ,  5.   ],
       [ 0.88 ,  0.   ,  2.6  , ...,  0.68 ,  9.8  ,  5.   ],
       [ 0.76 ,  0.04 ,  2.3  , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 0.51 ,  0.13 ,  2.3  , ...,  0.75 , 11.   ,  6.   ],
       [ 0.645,  0.12 ,  2.   , ...,  0.71 , 10.2  ,  5.   ],
       [ 0.31 ,  0.47 ,  3.6  , ...,  0.66 , 11.   ,  6.   ]])

In [53]:
y[0]

7.4

In [26]:
df1

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [59]:
from sklearn.linear_model import Lasso
Model2=Lasso(alpha=3)
Model2.fit(X_train,y_train)

Lasso(alpha=3)

In [60]:
Model2.predict([sample])

array([8.31693078])

In [61]:
# Ensemeble(Group) Learning: Group of algorithms help to get prediction 

In [62]:
# Bagging 
#     >RandomForestClassifier
#     >RandomForestRegressor
#     >BaggingClassifier
#     >BaggingRegressor
#     etc...

# Boosting
#     >AdaboostClassifier
#     >AdaBoostRegressor
#     etc...

# Stacking
#     >VottingClassifier
#     >VottingRegressor
#     etc...

In [2]:
# Bagging 
#     >RandomForestClassifier
#     >RandomForestRegressor
#     >BagginClassifier
#     >BoostingClassifier
#     etc...

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("iris.csv")

In [5]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [11]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
X_sc=sc.fit_transform(X)

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,train_size=0.8,random_state=42)


In [19]:
from sklearn.ensemble import RandomForestClassifier

In [71]:
Model3=RandomForestClassifier(n_estimators=100,max_depth=1) #untrained model
Model3.fit(X_train,y_train)   #trained model

RandomForestClassifier(max_depth=1)

In [52]:
import numpy as np
np.array([X_train[0]]).ndim

2

In [53]:
y_train[0]

'setosa'

In [54]:
Model3.predict([X_train[0]])

array(['setosa'], dtype=object)

In [55]:
Model3.predict_proba([X_train[0]])

array([[1., 0., 0.]])

In [56]:
X_train[10]

array([0.41666667, 0.29166667, 0.69491525, 0.75      ])

In [57]:
y_train[10]

'virginica'

In [58]:
Model3.predict([X_train[10]])

array(['virginica'], dtype=object)

In [59]:
Model3.predict_proba([X_train[10]])

array([[0., 0., 1.]])

In [60]:
df['species'].value_counts().index

Index(['setosa', 'versicolor', 'virginica'], dtype='object')

In [72]:
print("Training score:",Model3.score(X_train,y_train))

Training score: 0.95


In [73]:
print("Testing score : ", Model3.score(X_test,y_test))

Testing score :  0.9666666666666667


In [74]:
Model3.predict_proba([X_train[10]])

array([[0.00500095, 0.48828627, 0.50671278]])

In [75]:
Model3.predict_proba([X_train[2]])

array([[0.02449241, 0.50619091, 0.46931668]])

In [82]:
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
week=LogisticRegression(max_iter=200)
Model4=BaggingClassifier(estimator=week,n_estimators=100)
Model4.fit(X_train,y_train)

BaggingClassifier(estimator=LogisticRegression(max_iter=200), n_estimators=100)

In [83]:
Model4.score(X_train,y_train)

0.925

In [84]:
Model4.score(X_test,y_test)

0.9666666666666667

In [1]:
# Boosting
#     >AdaboostClassifier
#     >AdaBoostRegressor
#     etc...

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("iris.csv")

In [4]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [8]:
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [10]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
X_sc=sc.fit_transform(X)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,random_state=42)

In [31]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [34]:

Model5=AdaBoostClassifier(estimator=LogisticRegression(max_iter=200),n_estimators=100,learning_rate=0.0001)  # untrained model
Model5.fit(X_train,y_train)  # trained model

AdaBoostClassifier(estimator=LogisticRegression(max_iter=200),
                   learning_rate=0.0001, n_estimators=100)

In [35]:

Model6=AdaBoostClassifier(estimator=RandomForestClassifier(),n_estimators=100,learning_rate=0.0001)  # untrained model
Model6.fit(X_train,y_train)  # trained model

AdaBoostClassifier(estimator=RandomForestClassifier(), learning_rate=0.0001,
                   n_estimators=100)

In [29]:
Model5.score(X_train,y_train)

0.9107142857142857

In [30]:
Model5.score(X_test,y_test)

0.8947368421052632

In [36]:
Model6.score(X_train,y_train)

1.0

In [37]:
Model6.score(X_test,y_test)

1.0

In [38]:
# Stacking
#     >VottingClassifier
#     >VottingRegressor
#     etc...

In [40]:
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
week1=LogisticRegression(max_iter=200)
week2=RandomForestClassifier()
week3=AdaBoostClassifier()
week4=KNeighborsClassifier(n_neighbors=10)
week5=DecisionTreeClassifier()
Model7=VotingClassifier(estimators=[("m1",week1),("m2",week2),("m3",week3),("m4",week4),("m5",week5)])
Model7.fit(X_train,y_train)

VotingClassifier(estimators=[('m1', LogisticRegression(max_iter=200)),
                             ('m2', RandomForestClassifier()),
                             ('m3', AdaBoostClassifier()),
                             ('m4', KNeighborsClassifier(n_neighbors=10)),
                             ('m5', DecisionTreeClassifier())])

In [42]:
Model7.score(X_train,y_train)

0.9910714285714286

In [43]:
Model7.score(X_test,y_test)

1.0

In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import cv2

In [3]:
pip install cv2

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
